server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php;

    client_max_body_size 132M;

    charset utf-8;

    location /storage/ {
        alias /var/www/html/storage/app/public/;
        expires 30d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        
        fastcgi_param  HTTPS on;
        fastcgi_param  HTTP_X_FORWARDED_PROTO https;

        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
